### ISSUE TITLE
GT911 interrupt mode

### ISSUE THREAD

**Issue by chconnor** [DeanK2022/GT911#1]
Just wanted to pop in to say -- I've been on the hunt for the reason the GT911 doesn't seem to work in interrupt mode. I have a half-baked theory: the GT911 chip has a "VDDIO" pin; if it is left floating, then the outputs of the GT911 (including, I assume, the INT line) only get to about 1.5V max, which isn't enough to be a "HIGH" for 3.3V logic. If VDDIO is tied to the 3.3V feeding the GT911, then it outputs a normal HIGH. My (total) guess is that the vendors that are including the chip are leaving VDDIO floating.

The screen I use ([DFR0669](https://wiki.dfrobot.com/3.5inches_480_320_TFT_LCD_Capacitive_Touchscreen_SKU_DFR0669)) also has a level-shifting chip in between the GT911 and the "INT" on the board, and I think that may be squelching the INT all the way to LOW if it's not high enough for the level-shifting chip to read as HIGH. I.e. I don't think I could even use a scope to check if my theory is right.

If you have a scope you might try watching the INT line to see if it moves at all. (But of course you have to set the appropriate register in module_switch1 register in the config block to start interrupt mode.)

Also you mentioned that the I2C address selection was a bit random -- I wonder if, like mine, your screen module has some intervening level-shifting between the module's "INT" pin and the GT911 INT that might mess up the way INT is used to select the I2C address at initialization. Just spitballing.

**Comment by DeanK2022** [comment]
Sadly I have no scope and pretty much left it when the vendor told me not to use the INT method!

I just thought the I2C addressing was whatever state the chip was in on startup, residual electric or something meaning it is undefined until you set it.  No matter, best practice is to either set it or discover it, and that works.

Thanks for your comment though @chconner, much appreciated.  This has been quite the journey of sailing the seas of ignorance in a boat made of stupidity; I am a programmer not an electronics wiz.

**Comment by DeanK2022** [comment]
Discussion inconclusive
